---
title: "BehavioralAnalysisRTAfterIncorrect"
author: "Jonathan"
date: "2024-06-03"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(reshape2)
library(broom)
library(lmerTest)

```


```{r}
# Loading data
df1 <- read.csv("../data_behavioral/1_corrected_behav.csv")
df2 <- read.csv("../data_behavioral/2_corrected_behav.csv")

```

```{r}
# Creating correct reaction time
df1$RT <- (df1$ReactionTime - df1$PredOnset)
df2$RT <- (df2$ReactionTime - df2$PredOnset)
```

```{r}
# For df1
IncList1 <- df1[df1$Correct == 0,]
NextTrialInd1 <- IncList1$Trial + 1
NextTrialInd1 <- NextTrialInd1[NextTrialInd1 <= nrow(df1)]

NextTrials1 = df1[NextTrialInd1,]
```

```{r}
# For df2
IncList2 <- df2[df2$Correct == 0,]
NextTrialInd2 <- IncList2$Trial + 1
NextTrialInd2 <- NextTrialInd2[NextTrialInd2 <= nrow(df2)]

NextTrials2 = df2[NextTrialInd2,]
```

```{r}
# Creating dataframe for all other trials
all_trials_indices1 <- df1$Trial

# Step 2: Use setdiff to find the trials that are not in NextTrialInd1
other_trial_indices1 <- setdiff(all_trials_indices1, NextTrialInd1)

# Step 3: Subset df1 using these indices
OtherTrial1 <- df1[df1$Trial %in% other_trial_indices1, ]
```

```{r}
# Step 1: Identify the indices of all trials
all_trials_indices2 <- df2$Trial

# Step 2: Use setdiff to find the trials that are not in NextTrialInd2
other_trial_indices2 <- setdiff(all_trials_indices2, NextTrialInd2)

# Step 3: Subset df2 using these indices
OtherTrial2 <- df2[df2$Trial %in% other_trial_indices2, ]
```

```{r}
NextTrials1$Group <- "RT_AfterIncorrect_A"
OtherTrial1$Group <- "RT_AfterCorrect_A"
NextTrials2$Group <- "RT_AfterIncorrect_B"
OtherTrial2$Group <- "RT_AfterCorrect_B"
```

```{r}
# Creating data frame with all
combined_data <- rbind(NextTrials1, OtherTrial1, NextTrials2, OtherTrial2)

combined_data$Group <- factor(combined_data$Group, levels = c("RT_AfterIncorrect_A", "RT_AfterCorrect_A", "RT_AfterIncorrect_B", "RT_AfterCorrect_B"))


```

```{r}
AI_plot <- ggplot(combined_data, aes(x = Group, y = RT, fill = Group)) +
  geom_boxplot() +
  labs(title = "",
       x = "Participant and Category",
       y = "Reaction Time")

```

```{r}

ggsave("reaction_times_plot.png", plot = AI_plot, width = 10, height = 6, units = "in")


```



```{r}

df_comb_1 <- filter(combined_data, Group == c("OtherTrials1") | Group == c("AfterInc1"))

df_comb_2 <- filter(combined_data, Group == c("OtherTrials2") | Group == c("AfterInc2"))

```




```{r}

glm_model1 <- glm(log(RT) ~ Group, data = df_comb_1, family = gaussian)

summary(glm_model1)

```

```{r}

glm_model2 <- glm(log(RT) ~ Group, data = df_comb_2, family = gaussian)


summary(glm_model1)
summary(glm_model2)

```



```{r}

glm_modelp1 <- glm(RT ~ Group, data = df_comb_1, family = Gamma)

summary(glm_modelp1)


```


```{r}
glm_modelp2 <- glm(RT ~ Group, data = df_comb_2, family = Gamma)


summary(glm_modelp2)
```

```{r}

tidy_modelg1 <- tidy(glm_modelp1)
tidy_modelg2 <- tidy(glm_modelp2)

tidy_modelg1$model <- "modelg1"
tidy_modelg2$model <- "modelg2"

combined_results <- rbind(tidy_modelg1, tidy_modelg2)

write.csv(combined_results, "combined_model_results_AI.csv", row.names = FALSE)


```













