---
title: "BehavioralAnalysisRT"
author: "Jonathan"
date: "2024-06-03"
output: html_document
---
```{r}

library(tidyverse)
library(dplyr)
library(reshape2)


```

```{r}
# Loading data
df1 <- read.csv("../data_behavioral/1_corrected_behav.csv")
df2 <- read.csv("../data_behavioral/2_corrected_behav.csv")

```

```{r}
# Creating correct reaction time
df1$RT <- (df1$ReactionTime - df1$PredOnset)
df2$RT <- (df2$ReactionTime - df2$PredOnset)

```



```{r}
# Isolating volatile part and stable part
df1_vol <- df1[51:100,]
df2_vol <- df2[51:100,]

df1_stb <- df1[1:50,]
df2_stb <- df2[1:50,]

```

```{r}
# Takind average reaction time for volatile environment
avg_RT1_vol <- mean(df1_vol$RT)
avg_RT2_vol <- mean(df2_vol$RT)

# Taking average reaction time for stable environment
avg_RT1_stb <- mean(df1_stb$RT)
avg_RT2_stb <- mean(df2_stb$RT)

```


```{r}
# Creating dataframe with only the interesting columns
df_bx <- tibble(RT_A_vol = df1_vol$RT, RT_A_stb = df1_stb$RT, RT_B_vol = df2_vol$RT, RT_B_stb = df2_stb$RT)

df_bx <- na.omit(df_bx)



```

```{r}

df_long <- melt(df_bx, measure.vars = c("RT_A_vol", "RT_A_stb", "RT_B_vol", "RT_B_stb"))

```



```{r}

# Creating the scatter plot with standard errors
RT_vs <- ggplot(df_long, aes(x = variable, y = value, fill = variable)) +
  geom_boxplot() +
  labs(title = "Reaction Times in Stable and Volatile Environment", x = "Participant and Category", y = "Reaction Time")
  
  
```


```{r}

RT_vs
ggsave("reaction_times_plot.png", plot = RT_vs, width = 10, height = 6, units = "in")

ggsave("reaction_times_plot.png", plot = plot, width = 10, height = 6, units = "in")

getwd()
```


```{r}
df_long <- melt(df_bx, measure.vars = c("RT_A_stb", "RT_A_vol", "RT_B_stb", "RT_B_vol"))


```


```{r}

df_1_long <- filter(df_long, variable %in% c("RT_A_stb", "RT_A_vol"))

df_2_long <- filter(df_long, variable %in% c("RT_B_stb", "RT_B_vol"))


```

```{r}

modell1 <- glm(log(value) ~ variable, data = df_1_long, family = gaussian)

summary(modell1)


```

```{r}
modell2 <- glm(log(value) ~ variable, data = df_2_long, family = gaussian)

summary(modell2)


```

```{r}

modelg1 <- glm(value ~ variable, data = df_1_long, family = Gamma)

summary(modelg1)


```

```{r}

modelg2 <- glm(value ~ variable, data = df_2_long, family = Gamma)

summary(modelg2)


```

```{r}
tidy_modelg1 <- tidy(modelg1)
tidy_modelg2 <- tidy(modelg2)

tidy_modelg1$model <- "modelg1"
tidy_modelg2$model <- "modelg2"

combined_results <- rbind(tidy_modelg1, tidy_modelg2)

write.csv(combined_results, "combined_model_results.csv", row.names = FALSE)
```
















